# Generated by Django 5.2 on 2025-09-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ENV_VAR", "Environment Variable"),
                            ("PROMPT", "Code/AI Prompt"),
                            ("DOC_LINK", "Documentation Link"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("DEV", "Development"),
                            ("STAGING", "Staging"),
                            ("PROD", "Production"),
                        ],
                        default="DEV",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("key", models.CharField(blank=True, max_length=255)),
                ("value", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "workspace_env",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="workspaces.workspaceenvironment",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArtifactTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_tags",
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_tags",
                        to="artifacts.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["artifact_id", "tag_id"],
            },
        ),
        migrations.AddField(
            model_name="artifact",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="artifacts",
                through="artifacts.ArtifactTag",
                to="artifacts.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["workspace", "name"], name="artifacts_t_workspa_6a6b9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="artifacttag",
            index=models.Index(
                fields=["artifact", "tag"], name="artifacts_a_artifac_9ae910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifacttag",
            index=models.Index(
                fields=["tag", "artifact"], name="artifacts_a_tag_id_bafe4d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artifacttag",
            unique_together={("artifact", "tag")},
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["workspace", "kind"], name="artifacts_a_workspa_4e1932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["workspace", "environment"],
                name="artifacts_a_workspa_353865_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["workspace_env"], name="artifacts_a_workspa_2a02cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["kind", "-updated_at"], name="artifacts_a_kind_44ae0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["workspace", "kind", "environment"],
                name="artifacts_a_workspa_8f27bb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "ENV_VAR"), models.Q(("key", ""), _negated=True)
                ),
                fields=("workspace", "kind", "key", "environment"),
                name="unique_env_var_key_per_workspace_environment",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind__in", ["PROMPT", "DOC_LINK"]),
                    models.Q(("title", ""), _negated=True),
                ),
                fields=("workspace", "kind", "title", "environment"),
                name="unique_title_per_workspace_environment_and_kind",
            ),
        ),
    ]
