# Generated by Django 5.1.2 on 2025-10-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REVEAL_VALUE', 'Revealed ENV_VAR value'), ('CREATE', 'Created artifact'), ('UPDATE', 'Updated artifact'), ('DELETE', 'Deleted artifact')], help_text='Type of action performed', max_length=50)),
                ('user_uid', models.CharField(help_text='Firebase UID of user who performed action', max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., changed fields, reason)')),
                ('artifact', models.ForeignKey(help_text='The artifact that was accessed', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='artifacts.artifact')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['artifact', '-timestamp'], name='artifacts_a_artifac_fa0d1d_idx'), models.Index(fields=['user_uid', '-timestamp'], name='artifacts_a_user_ui_9fb859_idx')],
            },
        ),
    ]
