# Nixpacks configuration for Railway deployment
# This file controls how Railway builds and runs the Django application

[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
# Remove collectstatic from build phase since it needs environment variables
# We'll run it in the start command instead
cmds = []

[start]
# Run migrations and collectstatic at startup (when env vars are available)
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn deadline_api.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60 --access-logfile - --error-logfile -"
