# Generated by Django 5.2 on 2025-09-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=20, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Workspace name (e.g., 'E-commerce API', 'Frontend Dashboard')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the workspace purpose",
                    ),
                ),
                (
                    "owner_uid",
                    models.CharField(
                        db_index=True,
                        help_text="Firebase UID of the workspace owner",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "name"],
                "indexes": [
                    models.Index(
                        fields=["owner_uid"], name="workspaces__owner_u_11feed_idx"
                    ),
                    models.Index(
                        fields=["owner_uid", "-updated_at"],
                        name="workspaces__owner_u_f243e3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_uid", "name"),
                        name="unique_workspace_name_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceEnvironment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "environment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_environments",
                        to="workspaces.environmenttype",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_environments",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace_id", "environment_type_id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "environment_type"],
                        name="workspaces__workspa_9ad859_idx",
                    )
                ],
                "unique_together": {("workspace", "environment_type")},
            },
        ),
    ]
